version: '2'

services:
  vim:
    build:
      context: .
      args:
        - INSTALL_SPACEVIM=true
    container_name: myvim
    volumes:
       - ./vim/vimrc.conf:/root/.vimrc
       - ./vim/vim:/root/.vim/
       - ./test/:/mnt/test
       - /mnt/WEBSITE/:/mnt/WEBSITE

