version: '2'

services:
  vim:
    build:
      context: .
      args:
        - INSTALL_SPACEVIM=true
    container_name: myvim
    volumes:
       - ./vim/:/root/
       - /mnt/WEBSITE/:/mnt/WEBSITE/

