version: '2'

services:

  workspace:
    build: ./workspace
    volumes:
       - ./vim/vimrc.conf:/root/.vimrc
       - ./vim/vim:/root/.vim/
       - ./test/:/mnt/test
       - /mnt/WEBSITE/:/mnt/WEBSITE

